language: node_js
node_js:
   - "0.8"
   - "0.10"

notifications:
  email: false

services:
  - mongodb

env:
  global:
    - NODE_ENV=test

before_script:
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cd api && npm install && node server.js &"
  - "sleep 10"
  - "cd ./casperjs && git checkout tags/1.0.2 && cd .."

script:
  - "DISPLAY=:99.0 make all_tests"