/*
       Licensed to the Apache Software Foundation (ASF) under one
       or more contributor license agreements.  See the NOTICE file
       distributed with this work for additional information
       regarding copyright ownership.  The ASF licenses this file
       to you under the Apache License, Version 2.0 (the
       "License"); you may not use this file except in compliance
       with the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing,
       software distributed under the License is distributed on an
       "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
       KIND, either express or implied.  See the License for the
       specific language governing permissions and limitations
       under the License.
 */

package de.mwager.atonego;

// bugsense
// import com.bugsense.trace.BugSenseHandler;

import android.os.Bundle;
import org.apache.cordova.*;

public class atonego extends DroidGap
{
    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);

        // Set by <content src="index.html" /> in config.xml
        // super.loadUrl(Config.getStartUrl());
        // super.loadUrl("file:///android_asset/www/index.html")

        // from jqm docs:
        // http://jquerymobile.com/demos/1.2.0-alpha.1/docs/pages/phonegap.html
        // Android enforces a timeout when loading URLs in a webview which may
        // be too short for your needs. You can change this timeout by editing a
        // Java class generated by the Eclipse plugin for Android:
        // UPDATE DEPRECATED!?!? use config.xml ab AUG-2013 ?!?
        // super.setIntegerProperty("loadUrlTimeoutValue", 60000);

        // --- splashscreen support ---
        // Dateiname muss splashscreen.XXX sein!
        super.setIntegerProperty("splashscreen", R.drawable.splashscreen);
        // SOLANGE WIRD ER ANGEZEIGT - bei Aufruf von navigator.splashscreen.show();
        super.loadUrl(Config.getStartUrl(), 10000); // TODO NEEDED AGAIN!?
    }
}

